name: test env actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hi ${{ vars.main.CYPRESS_RECORD_KEY }}'
      - run: echo 'Hi ${{ vars.main.IS_CYPRESS_RECORDED }}'
