name: test env actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CYPRESS_RECORD_KEY: 'cypress-record-key'
  IS_CYPRESS_RECORDED: false

jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hi ${{ env.CYPRESS_RECORD_KEY }}'
      - run: echo 'Hi ${{ env.IS_CYPRESS_RECORDED }}'
