name: test env actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hi ${{ vars.CYPRESS_RECORD_KEY }}'
      - run: echo 'Hi ${{ vars.IS_CYPRESS_RECORDED }}'
